### ISSUE TITLE
lmc.go.enrichment error with mm10 WGBS data

### ISSUE THREAD

**Issue by HeyLifeHD** [lutsik/MeDeCom#33] opened 2020-03-06 16:18 UTC
Dear Michael,

I noticed an error running lmc.go.enrichment on a medecom result created with average methylation values of regions (instead of single CpGs) originated from WGBS mouse data.

```
> go_enrich_median_05_hypo <- lmc.go.enrichment(medecom.result, anno.data= anno,
+        K = 5, lambda = 0.01,  diff.threshold = 0.2,
+        reference.computation = "median", 
+        region.type = "genes",  type = "hypo",
+        assembly = "mm10")
<simpleError in getUniverseHelper(probes, datPkg, entrezIds): After filtering, there are no valid IDs that can be used as the Gene universe.
  Check input values to confirm they are the same type as the central ID used by your annotation package.
  For chip packages, this will still mean the central GENE identifier used by the package (NOT the probe IDs).>
[1] "LMC 1 processed"
<simpleError in getUniverseHelper(probes, datPkg, entrezIds): After filtering, there are no valid IDs that can be used as the Gene universe.
  Check input values to confirm they are the same type as the central ID used by your annotation package.
  For chip packages, this will still mean the central GENE identifier used by the package (NOT the probe IDs).>
[1] "LMC 2 processed"
<simpleError in getUniverseHelper(probes, datPkg, entrezIds): After filtering, there are no valid IDs that can be used as the Gene universe.
  Check input values to confirm they are the same type as the central ID used by your annotation package.
  For chip packages, this will still mean the central GENE identifier used by the package (NOT the probe IDs).>
[1] "LMC 3 processed"
<simpleError in getUniverseHelper(probes, datPkg, entrezIds): After filtering, there are no valid IDs that can be used as the Gene universe.
  Check input values to confirm they are the same type as the central ID used by your annotation package.
  For chip packages, this will still mean the central GENE identifier used by the package (NOT the probe IDs).>
[1] "LMC 4 processed"
<simpleError in getUniverseHelper(probes, datPkg, entrezIds): After filtering, there are no valid IDs that can be used as the Gene universe.
  Check input values to confirm they are the same type as the central ID used by your annotation package.
  For chip packages, this will still mean the central GENE identifier used by the package (NOT the probe IDs).>
[1] "LMC 5 processed"
Warning messages:
1: In makeValidParams(.Object) : removing duplicate IDs in geneIds
2: In makeValidParams(.Object) : removing duplicate IDs in universeGeneIds
3: In makeValidParams(.Object) : removing duplicate IDs in geneIds
4: In makeValidParams(.Object) : removing duplicate IDs in universeGeneIds
5: In makeValidParams(.Object) : removing duplicate IDs in geneIds
6: In makeValidParams(.Object) : removing duplicate IDs in universeGeneIds
7: In makeValidParams(.Object) : removing duplicate IDs in geneIds
8: In makeValidParams(.Object) : removing duplicate IDs in universeGeneIds
9: In makeValidParams(.Object) : removing duplicate IDs in geneIds
10: In makeValidParams(.Object) : removing duplicate IDs in universeGeneIds
> traceback()
17: goids %in% ontIds
16: FUN(X[[i]], ...)
15: lapply(as.list(env), FUN, ...)
14: lapply(as.list(env), FUN, ...)
13: eapply(ID2GO(datPkg), function(goids) {
        if (length(goids) == 0 || (length(goids) == 1 && is.na(goids))) 
            return(FALSE)
        if (!is.character(goids[[1]])) 
            goids <- subListExtract(goids, "GOID", simplify = TRUE)
        if (any(goids %in% ontIds)) 
            return(TRUE)
        FALSE
    })
12: eapply(ID2GO(datPkg), function(goids) {
        if (length(goids) == 0 || (length(goids) == 1 && is.na(goids))) 
            return(FALSE)
        if (!is.character(goids[[1]])) 
            goids <- subListExtract(goids, "GOID", simplify = TRUE)
        if (any(goids %in% ontIds)) 
            return(TRUE)
        FALSE
    })
11: getUniverseViaGo(p)
10: universeBuilder(p)
9: universeBuilder(p)
8: .hyperGTestInternal(p, "GOHyperGResult", getGoToChildGraph)
7: hyperGTest(params)
6: hyperGTest(params)
5: doTryCatch(return(expr), name, parentenv, handler)
4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
3: tryCatchList(expr, classes, parentenv, handlers)
2: tryCatch(hyperGTest(params), error = function(e) {
       print(e)
   })
1: lmc.go.enrichment(medecom.result, anno.data = anno, K = 5, lambda = 0.01, 
       diff.threshold = 0.2, reference.computation = "median", region.type = "genes", 
       type = "hypo", assembly = "mm10")
````
Let me know if you need some of the data to reproduce the error. I think if in general the universe is the problem, all genes could be used by default.

Thanks for your support.

Best,

Joschka

**Comment by schmic05** [comment] 2020-03-07 09:27
Hi Joschka,

Thanks for reporting this. Do you have the "org.Mm.eg.db" package installed? It might be that we have not properly tested whether the package is installed within MeDeCom. 

If this is not the problem, it would be great if you could share some data to reproduce the error with me, since I do not have (easy) access to mouse data.

Best,

Michael

**Comment by HeyLifeHD** [comment] 2020-03-07 11:02
Hi Michael,

org.Mm.eg.db should be installed. I will forward you some example data (medecom result as well as region annotation as rds files) to your email. 

Thanks and best wishes,

Joschka

**Comment by schmic05** [comment] 2020-03-09 14:51
Fixed with https://github.com/lutsik/MeDeCom/commit/50a652522c4fc63fbe03811b43313d2bc924fb96

**Closed as completed by schmic05** 2020-03-09 14:51 UTC
